services:
  - type: web
    name: strategy-trader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET
        sync: false
      - key: PORT
        value: 5000
